language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: BkIvupriW8BK6ESmlKleZiJPZkZ753n2wa4j/lL15mPm7MNBjvlWxD3mb0z/CRR70IBWAc/RrcYdHNF3RUqcGva0KCXaas3I2a1oGgi+4R7dHGf1GZYAR3/2Rn33gxsQeanAdTmMSMRQAlTJfup8qUdF4iHWfpq/qBbnc2xZKu5BFIiyWbJY3tyFzTq0ZXM1ZMhujhte0oJZIerDowA/0H4Dvvjwm0E7EdaILnJY7gMfPKAd0bl49jcdOOXth7WJdTIRogpKfb/sD8qVDne0GrbTkAKlRSAIvtdTBbAu9e89hqeGHhx6eb8ApN/a+UMMT13jr7d5RBjjmHk8h9otbwFenL3Dw7ux6U5E2Rb0p6b4hZdVfQCD/7QG5r0jAPjKznis6//5Ad5Fxp0PqyzwzA1vllUKL0Tn1f4tOZYkN+RvBpid3kdgQDyLOfEiv/U2W+yQiigq9t8LlAo8++RzGUvZy6VN5WleDXWc1VK/KOkLtQ8nwN3yMmdauE5jYDJOWOQWX68AJh4LRmMecz5kg5RDQEqgzDlKjYyUl1elatFnUKwTNM5F4VVqu/ytEZA/eJBggOgpbnzr1hvvjd4dJHrex8PT/XVgv/15EpBDIs4yJlUwZkzVjIxoR+Y0KgtX1AYWQUwAH/n7hBnEP4EY67siML1E2fmSgD6i8JKfq3I=
  app: enigmatic-eyrie-64422
